baseURL = "https://marcbenedi.github.io/blog/"
languageCode = "en-us"
publishDir = "docs"
theme = "terminal"
paginate = 5

[languages]
  [languages.en]
    title = "Î»"
    subtitle = "marcb's blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd ~"
      logoHomeLink = "https://marcbenedi.github.io/blog/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Visit marcb.pro page"
        url = "http://marcb.pro/"
