title = "Î»"
subtitle = "marcb's blog"
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[params.logo]
  logoText = "$ cd ~"
  logoHomeLink = "https://marcbenedi.github.io/blog/"
