title = "λ"
subtitle = "marcb's blog"
keywords = ""
copyright = "Copyright © blog.marcb.pro 2020"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[params.logo]
  logoText = "$ cd ~"
  logoHomeLink = "http://blog.marcb.pro/"
