[[main]]
  identifier = "about"
  name = "About me"
  url = "http://marcb.pro/"

# [[main]]
#   identifier = "algorithms"
#   name = "Algorithms"
#   url = "/posts/algorithms"

[[main]]
  identifier = "linux"
  name = "Linux"
  url = "/posts/linux/"
