# dir name of your blog content (default is `content/posts`)
contentTypeName = "posts"
# ["orange", "blue", "red", "green", "pink"]
themeColor = "organge"
# if you set this to 0, only submenu trigger will be visible
showMenuItems = 4
# set theme to full screen width
fullWidthTheme = true
# center theme with default width
centerTheme = true
# set a custom favicon (default is a `themeColor` square)
# favicon = "favicon.ico"
